apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: satellite
spec:
  ports:
  - name: grpc
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: satellite
  sessionAffinity: None
  type: ClusterIP
